import { BifrostFormQuestionWithEmailResponse, BifrostFormQuestionWithPhoneNumberResponse, BifrostFormQuestionWithSplitTextResponse, BifrostFormQuestionWithTextResponse } from "@/models/BifrostFormQuestions/BifrostFormQuestionWithResponse";
export declare const mockBifrostFormQuestionWithTextResponseOne: BifrostFormQuestionWithTextResponse;
export declare const mockBifrostFormQuestionWithTextResponseTwo: BifrostFormQuestionWithTextResponse;
export declare const mockBifrostFormQuestionWithTextResponseThree: BifrostFormQuestionWithTextResponse;
export declare const mockBifrostFormQuestionWithEmailResponseOne: BifrostFormQuestionWithEmailResponse;
export declare const mockBifrostFormQuestionWithPhoneNumberResponseOne: BifrostFormQuestionWithPhoneNumberResponse;
export declare const mockBifrostFormQuestionWithSplitTextResponseOne: BifrostFormQuestionWithSplitTextResponse;
