export enum BifrostFormApplicationStage {
  LAUNCH_SCREEN = "LAUNCH_SCREEN",
  QUESTION_LOOP_SCREEN = "QUESTION_LOOP_SCREEN",
  ITINERARY_OFFER_PRESENTATION_SCREEN = "ITINERARY_OFFER_PRESENTATION_SCREEN",
}
