export enum BifrostFormApplicationStage {
  LAUNCH_SCREEN = "LAUNCH_SCREEN",
  INTERACTIVE_LOOP_SCREEN = "INTERACTIVE_LOOP_SCREEN",
  ITINERARY_OFFER_PRESENTATION_SCREEN = "ITINERARY_OFFER_PRESENTATION_SCREEN",
}
